receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  otlphttp/supabase_logs:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/logs
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

  otlphttp/supabase_traces:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/traces
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

  otlphttp/supabase_metrics:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/metrics
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_traces]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_logs]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_metrics]
