receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  otlphttp/supabase_logs:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/logs
    encoding: json
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

  otlphttp/supabase_traces:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/traces
    encoding: json
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

  otlphttp/supabase_metrics:
    endpoint: https://oqrqdofbtytcihfttlau.supabase.co/functions/v1/otel/v1/metrics
    encoding: json
    compression: none
    headers:
      apikey: "${SUPABASE_SERVICE_ROLE_KEY}"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_logs]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_traces]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/supabase_metrics]
